apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-observability
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: python-observability
  template:
    metadata:
      labels:
        app: python-observability
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
