apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetrygen
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telemetrygen
  template:
    metadata:
      labels:
        app: telemetrygen
    spec:
      containers:
      - name: telemetrygen
        image: ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen:latest
        args: ["traces", "--otlp-insecure", "--otlp-endpoint=adot-collector:4317", "--rate=5", "--duration=10m"]
